"""add rating int to products

Revision ID: 45698f9d73ad
Revises: 
Create Date: 2020-02-05 23:53:26.134481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45698f9d73ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'rating')
    # ### end Alembic commands ###
